// Generated by https://quicktype.io

export interface LocationResponse {
  id:      number;
  name:    string;
  region:  string;
  country: string;
  lat:     number;
  lon:     number;
  url:     string;
}
